### ISSUE TITLE
wrong path

### ISSUE THREAD

**Issue by NovaOnce** [realKarthikNair/GBoard-Dictionary-Maker#14]
When I run it on Android it creates a path I don't have. I can't find it with my Total Commander wich shows hidden files. Can you add a possibility to enter the path manually whenever is needed, so it doesn't force you to save .txt to the default path for Linux. Thanks 🙏

**Comment by realKarthikNair** [comment]
Please confirm if you're using the legacy branch for Android. The main branch is never intended for Android users.

**Comment by NovaOnce** [comment]
The problem is not what I use, but what I can't use. I can't choose the path or change it. It's a program who does it on its own. The path to the file: " '/data/user/0/etcetera". Maybe the button should be "save to" and you can confirm or change the path each time you save your file? Thanks!
And I didn't understood what symbols are used in gboard txt file in between words and at the end of lines. Can you tell?

**Comment by realKarthikNair** [comment]
Apologies for the issues you're facing.
Thank you for responding.
Can you send a screenshot for reference?

**Comment by realKarthikNair** [comment]
@Karcocha Kindly have a look at this.... I still don't understand what exactly are you facing.
https://github.com/realKarthikNair/GBoard-Dictionary-Maker/blob/7e63420c3fef09654027aa71bad8ea6e9b1526f3/functions.py#L10

**Comment by Karcocha** [comment]
Yeah. I see it in your code, but have a look at this. It's whenever I run a program. Screenshot 
![Screenshot_20220719-225246_Pydroid 3](https://user-images.githubusercontent.com/60623705/179846664-3afec0fe-3b55-405e-b723-2e75d7eee878.jpg)

**Comment by NovaOnce** [comment]
So... It goes like this when you:
1. Create a new one.
2. Save.
3. Browse.
![Screenshot_20220719-231133_Pydroid 3](https://user-images.githubusercontent.com/60623705/179849921-5b103755-6d27-421f-a403-80119d74e552.jpg)
![Screenshot_20220719-231215_Pydroid 3](https://user-images.githubusercontent.com/60623705/179849954-3fc89646-7e9c-4fa0-a235-2a3d0a7c3d0d.jpg)
![Screenshot_20220719-231237_Pydroid 3](https://user-images.githubusercontent.com/60623705/179849988-17d1299c-8cb1-4fbd-9f67-1ff688b273f3.jpg)

**Comment by NovaOnce** [comment]
Resolved!
It was a terminal directory. Emulated in app file directory. I have all files there.

**Comment by realKarthikNair** [comment]
Cool
